/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20Sol from "./ERC20.sol";
export type { erc20Sol };
import type * as medicineSupplySol from "./MedicineSupply.sol";
export type { medicineSupplySol };
export type { MedicsBook } from "./MedicsBook";
