/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IMedicsBook__factory } from "./IMedicsBook__factory";
export { MedicineSupply__factory } from "./MedicineSupply__factory";
