/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as erc20Sol from "./ERC20.sol";
export * as medicineSupplySol from "./MedicineSupply.sol";
export { MedicsBook__factory } from "./MedicsBook__factory";
